config/routes.rb
Rails.application.routes.draw do
  resources :payments
  #devise_for :admins
  devise_for :users
  resources :managers
  resources :orders
  resources :customers
  resources :menus
  resources :kitchen_staffs
  resources :waitstaffs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "managers#index"
  get 'pages/NutritionalInfo'
  get 'pages/Game1'
  get 'pages/Game2'
  get 'pages/Game3'
  get 'pages/ManagerOptions'
  get "/customers/welcome" => "customers#welcome"
  get "pages/CustomerHomepage" => "pages#CustomerHomepage"
   get 'pages/DailyRevenue'
  devise_for :admins do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
	has_many :menus
    accepts_nested_attributes_for :orders

end

app/models/kitchen_staff.rb
class KitchenStaff < ApplicationRecord
end

app/models/manager.rb
class Manager < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
mount_uploader :image, ImageUploader
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :customer, :optional => true
	has_many :menus
	accepts_nested_attributes_for :customer
	belongs_to :user, :optional => true
	#has_many :customers
end

app/models/payment.rb
class Payment < ApplicationRecord
has_many :orders, through: :customers
has_many :customers
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/waitstaff.rb
class Waitstaff < ApplicationRecord
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:remove_image, :image, :item_name, :item_description, :item_price, :item_picture)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @order = Order.all
    
    @customers = Customer.all
    #@order = Order.find(params[:customer_id])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
   
  end

  # GET /orders/new
  def new
    #@customer = Customer.find(params[:customer_id])
    #@order = @customer.orders.new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
   # @customer = Customer.new(customer_params)
    #@order = @customer.orders.new(order_params)
    #@order.save
    @order = Order.new(order_params)
   # @order.customer_names = customer_names
    respond_to do |format|
      if @order.save
        flash[:notice] = "Success!"
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_names, :tables, :customer_id, :notes)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def NutritionalInfo 
end

def Game1
end

def Game2
end

def Game3
end

def ManagerOptions

end

def DailyRevenue

	
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/happy_hour_helper.rb
module HappyHourHelper
end

app/helpers/kitchen_staffs_helper.rb
module KitchenStaffsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/waitstaffs_helper.rb
module WaitstaffsHelper
end

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class ="form-control-group">
    <%= form.file_field :image %>
    <% if @menu.image? %>
      <%= image_tag @menu.image.url, class: "menu-show" %>
      <%= form.check_box :remove_image %>
        Remove Image
      <% end %>
  </div>

  <div class="form-control-group">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, class: "form-control" %>
  </div>

  <div class="form-control-group">
    <%= form.label :item_description %>
    <%= form.text_area :item_description, class: "form-control" %>
  </div>

  <div class="form-control-group">
    <%= form.label :item_price %>
    <%= form.text_field :item_price, class: "form-control" %>
  </div>

  <!--<div class="form-control-group">
    <%= form.label :item_picture %>
    <%= form.text_field :item_picture %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<html>
<head>

<style>

    .menu-body {
  max-width: 680px;
  margin: 0 auto;
  display: block;
  color: rgb(92, 92, 92);
}

.menu-section {
  margin-bottom: 80px;
}

input[type=submit] {
    width: 15em;  height: 2em;
}

.menu-section-title {
  font-family: georgia;
  font-size: 50px;
  display: block;
  font-weight:normal;
  margin: 20px 0;
  text-align: Center;
}

.menu-item {
  margin: 35px 0;
  font-size: 18px;
}

.menu-item-name{
  font-family: helvetica;
  font-weight: bold;
  border-bottom: 2px dotted rgb(213, 213, 213);
}

.menu-item-description {
  font-style: italic;
  font-size: .9em;
  line-height: 1.5em;
}

.menu-item-price{
  float: right;
  font-weight: bold;
  font-family: arial;
  margin-top: -22px;
}




</style>





<div class="menu-body">
   <!-- Section starts: Appetizers -->
   <div class="menu-section">
      <h2 class="menu-section-title">APPETIZERS</h2>
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
             <form action="/menu/cart" method="post">
              <img src = "Vegetable-Spring-Rolls.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Vegetable-Spring-Rolls"value="Vegetable-Spring-Rolls"></input>
         </div>
         <div class="menu-item-price">
            $14.99
         </div>
         <div class="menu-item-description">
            Fried rice paper rolls | glass noodles | mixed vegetable | sweet & sour sauce. (4 pieces)

         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
              <img src = "corn patties.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Corn patties"value="Corn patties"></input>
         </div>
         <div class="menu-item-price">
            $14.99
         </div>
         <div class="menu-item-description">
            Everything you get in a traditional Crispy corn | sweet & sour sauce. (4 pieces)

         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
          <img src = "Gyoza.JPG" alt="Cinque Terre" width="300" height="200">
            <input type="submit" name="Gyoza"value="Gyoza"></input>
         </div>
         <div class="menu-item-price">
            $15.99
         </div>
         <div class="menu-item-description">
          Fried pork & vegetable pot stickers | soy sauce (6 pieces)
         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      
      <!-- Item ends -->
   </div>
   <!-- Section ends: Appetizers -->
   <!-- Section starts: Drinks -->
   <div class="menu-section">
      <h2 class="menu-section-title">DRINKS</h2>
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
           <img src = "hot green tea.JPG" alt="Cinque Terre" width="300" height="200">
            <input type="submit" name="Hot Green Teas" value="Hot Green Teas"></input>
         </div>
         <div class="menu-item-price">
            $12.99
         </div>
         <div class="menu-item-description">
           
         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
           <img src = "Thai Iced Tea.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Thai Iced Tea"value="Thai Iced Tea"></input>
         </div>
         <div class="menu-item-price">
            $12.99
         </div>
         <div class="menu-item-description">
          
         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
             <img src = "Soft Drinks.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Soft Drinks"value="Soft Drinks"></input>
             Coke, Diet Coke, Sprite and Dr.Pepper (Refills available for dine-in)
         </div>
         <div class="menu-item-price">
            $11.99
         </div>
         <div class="menu-item-description">
            
         </div>
      </div>


<div class="menu-item">
         <div class="menu-item-name">
           <img src = "water.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Water"value="Water"></input>
         </div>
         <div class="menu-item-price">
            $0.00
         </div>





<div class="menu-body">
   <!-- Section starts: Appetizers -->
   <div class="menu-section">
      <h2 class="menu-section-title">KIDS MENU</h2>
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
             <form action="/menu/cart" method="post">
              <img src = "Beef and Broccoli.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Beef and Broccoli"value="Beef and Broccoli"></input>
         </div>
         <div class="menu-item-price">
            $15.99
         </div>
         <div class="menu-item-description">
             White or brown steamed rice

         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
              <img src = "Orange Chicken.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Orange Chicken"value="Orange Chicken"></input>
         </div>
         <div class="menu-item-price">
            $15.99
         </div>
         <div class="menu-item-description">
             White or brown steamed rice


         </div>



         <div class="menu-item">
         <div class="menu-item-name">
              <img src = "Fried Rice.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Fried Rice"value="Fried Rice"></input>
         </div>
         <div class="menu-item-price">
            $15.99
         </div>
         <div class="menu-item-description">
           Scrambled eggs | Carrots | Peas

         </div>







         <div class="menu-body">
   <!-- Section starts: Appetizers -->
   <div class="menu-section">
      <h2 class="menu-section-title">DESSERTS</h2>
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
             <form action="/menu/cart" method="post">
              <img src = "Mango Sticky Rice.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Mango Sticky Rice"value="Mango Sticky Rice"></input>
         </div>
         <div class="menu-item-price">
            $15.99
         </div>
         <div class="menu-item-description">
             Mango | sweet sticky rice | coconut milk.


         </div>
      </div>
      <!-- Item ends -->
      <!-- Item starts -->
      <div class="menu-item">
         <div class="menu-item-name">
              <img src = "Custard sticky rice.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Custard sticky rice"value="Custard sticky rice"></input>
         </div>
         <div class="menu-item-price">
            $14.99
         </div>
         <div class="menu-item-description">
            Egg custard | sweet sticky rice | coconut milk.

         </div>



         <div class="menu-item">
         <div class="menu-item-name">
              <img src = "Green tea ice cream.JPG" alt="Cinque Terre" width="300" height="200">
             <input type="submit" name="Green tea ice cream "value="Green tea ice cream "></input>
         </div>
         <div class="menu-item-price">
            $14.50
         </div>
         <div class="menu-item-description">
            

         </div>
         </div>



      
         
<button type="submit" class="btn btn-success" >Checkout</button>
</form>


</head>
</body>
</html>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <!--<strong>Item name:</strong>-->
  <%= @menu.item_name %>
</h1>
</h2>
	<% if @menu.image? %> 
	<%= image_tag @menu.image.url, class: "menu-show" %>
	<% end %>
</h2>

<h5>
  <!--<strong>Item description:</strong>-->
  <%= @menu.item_description %>
  <%= "$" %> <%= @menu.item_price %>
</h5>



<!--<p>
  <strong>Item price:</strong>
  <%= @menu.item_price %>
</p>-->

<!--<p>
  <strong>Item picture:</strong>
  <%= @menu.item_picture %>
</p> -->
<%= link_to 'Add to Order', new_order_path %> |
<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %> |
<%= link_to 'Nutritional Info', pages_NutritionalInfo_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <%= form_for @order do |f| %>
  <!--<div class="field">
    <%= form.label :order_id %>
    <%= form.number_field :order_id %>
  </div> -->

  <div class="field">
    <%= form.label :customer_names %>
    <%= form.text_field :customer_names %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <!--<div class="field">
    <%= form.label :tables %>
    <%= form.number_field :tables %>
  </div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
      <% end %>

<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Customer names</th>
      <th>Customizations and Allergies</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @order.each do |order| %>
      <tr>
        <td><%= order.customer_names %></td>
        <td><%= order.notes %></td>

        <% if admin_signed_in? %>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %> |

<%= link_to 'Home', pages_CustomerHomepage_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>
<%= form_for @order do |f| %>
 <!-- <table summary="subject form fields">
    <tr>
      <th>Order</th>
      <td><%= f.text_field(:customer_names) %></td>
    </tr>
  </table>-->
<script>
function myFunction(int partySize) {
      /*  thisTable.setPartySize(partySize); 
      */
      int x = partySize; 
      //window.alert(x);
      document.getElementById("partySize").innerHTML = x;
      //Could maybe do a window alert for the coupon question?
      window.alert("");
      }
</script>


<div class='row'>
<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Table Number
  </button>
  <div class="dropdown-menu">
    <option class="dropdown-item" type="button">1</option>
    <button class="dropdown-item" type="button">2</button>
    <button class="dropdown-item" type="button">3</button>
    <button class="dropdown-item" type="button">4</button>
    <button class="dropdown-item" type="button">5</button>
    <button class="dropdown-item" type="button">6</button>
    <button class="dropdown-item" type="button">7</button>
    <button class="dropdown-item" type="button">8</button>
    <button class="dropdown-item" type="button">9</button>
    <button class="dropdown-item" type="button">10</button>
    <button class="dropdown-item" type="button">11</button>
    <button class="dropdown-item" type="button">12</button>
    <button class="dropdown-item" type="button">13</button>
    <button class="dropdown-item" type="button">14</button>
    <button class="dropdown-item" type="button">15</button>
    <button class="dropdown-item" type="button">16</button>

  </div>
</div>
<br>
<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Appetizers
  </button>
  <div class="dropdown-menu">
    <button class="dropdown-item" type="button">Veggie Spring rolls</button>
    <button class="dropdown-item" type="button">Corn Patties</button>
    <button class="dropdown-item" type="button">Gyoza</button>
	</div>
</div>

<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Entrees
  </button>
  <div class="dropdown-menu">
    <option class="dropdown-item" type="button">Pad Thai</option>
    <button class="dropdown-item" type="button">Yellow Curry</button>
    <button class="dropdown-item" type="button">Pad See Eew</button>
  </div>
</div>

<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Kids Menu
  </button>
   <div class="dropdown-menu">
    <option class="dropdown-item" type="button">Beef and Broccoli</option>
    <button class="dropdown-item" type="button">Orange Chicken</button>
    <button class="dropdown-item" type="button">Fried Rice</button>
  </div>
</div>

<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Desserts
  </button>
   <div class="dropdown-menu">
    <option class="dropdown-item" type="button">Mango sticky rice</option>
    <button class="dropdown-item" type="button">Custard Sticky Rice</button>
    <button class="dropdown-item" type="button">Green Tea Ice Cream</button>
   </div>
</div>


<div class="btn-group">
  <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Drinks
  </button>
   <div class="dropdown-menu">
    <option class="dropdown-item" type="button">Hot Tea</option>
    <button class="dropdown-item" type="button">Iced Tea</button>
    <button class="dropdown-item" type="button">Soft Drinks</button>
  </div>
</div>
</div>

<%= render 'form', order: @order %>
<% end %>


<%= link_to 'Back', orders_path %>-->

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Customer names:</strong>
  <%= @order.customer_names %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @order.notes %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>