config/routes.rb
Rails.application.routes.draw do
  resources :payments
  #devise_for :admins
  devise_for :users
  resources :managers
  resources :orders
  resources :customers
  resources :menus
  resources :kitchen_staffs
  resources :waitstaffs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "managers#index"
  get 'pages/NutritionalInfo'
  get 'pages/Game1'
  get 'pages/Game2'
  get 'pages/Game3'
  get 'pages/ManagerOptions'
  get "/customers/welcome" => "customers#welcome"
  get "pages/CustomerHomepage" => "pages#CustomerHomepage"
   get 'pages/DailyRevenue'
  devise_for :admins do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end

end

app/models/manager.rb
class Manager < ApplicationRecord
end

app/controllers/managers_controller.rb
defclass ManagersController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :destroy]
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:manager_name, :manager_pin)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_with(model: manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :manager_name %>
    <%= form.text_field :manager_name %>
  </div>

  <div class="field">
    <%= form.label :manager_pin %>
    <%= form.number_field :manager_pin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managers</h1>
<button type="button" class="btn btn-secondary btn-lg btn-block">
 <% if !admin_signed_in? %>
    <%= link_to 'log in',  new_admin_session_path%>
  <% end %>
  <% if admin_signed_in? %>
    <%= link_to 'log out',  destroy_admin_session_path, :method => :delete  %>
  <% end %>
</button>

<button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to 'Customer', customers_path  %></button>
<button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to 'Waitstaff', waitstaffs_path %></button>
<button type="button" class="btn btn-secondary btn-lg btn-block">
  <%= link_to 'Kitchen', kitchen_staffs_path  %></button>
<button type="button" class="btn btn-secondary btn-lg btn-block">
  <%= link_to 'Manager', pages_ManagerOptions_path%></button>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.manager_name %></td>
        <td><%= manager.manager_pin %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Manager', new_manager_path %> -->

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manager name:</strong>
  <%= @manager.manager_name %>
</p>

<p>
  <strong>Manager pin:</strong>
  <%= @manager.manager_pin %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>