config/routes.rb
Rails.application.routes.draw do
  resources :payments
  #devise_for :admins
  devise_for :users
  resources :managers
  resources :orders
  resources :customers
  resources :menus
  resources :kitchen_staffs
  resources :waitstaffs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "managers#index"
  get 'pages/NutritionalInfo'
  get 'pages/Game1'
  get 'pages/Game2'
  get 'pages/Game3'
  get 'pages/ManagerOptions'
  get "/customers/welcome" => "customers#welcome"
  get "pages/CustomerHomepage" => "pages#CustomerHomepage"
   get 'pages/DailyRevenue'
  devise_for :admins do
    get '/admins/sign_out' => 'admins/sessions#destroy'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :orders
	has_many :menus
    accepts_nested_attributes_for :orders

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    before_action :set_customer, only: [:show, :edit, :update, :destroy]
    
    # GET /customers
    # GET /customers.json
    def index
        @customers = Customer.all
    end
    
    # GET /customers/1
    # GET /customers/1.json
    def show
    end
    
    # GET /customers/new
    def new
        @customer = Customer.new
    end
    
    # GET /customers/1/edit
    def edit
    end
    
    # POST /customers
    # POST /customers.json
    def create
        @customer = Customer.new(customer_params)
        
        respond_to do |format|
            if @customer.save
                format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
                format.json { render :show, status: :created, location: @customer }
                else
                format.html { render :new }
                format.json { render json: @customer.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # PATCH/PUT /customers/1
    # PATCH/PUT /customers/1.json
    def update
        respond_to do |format|
            if @customer.update(customer_params)
                format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
                format.json { render :show, status: :ok, location: @customer }
                else
                format.html { render :edit }
                format.json { render json: @customer.errors, status: :unprocessable_entity }
            end
        end
    end
    
    # DELETE /customers/1
    # DELETE /customers/1.json
    def destroy
        @customer.destroy
        respond_to do |format|
            format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
    
    private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
        @customer = Customer.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
        params.require(:customer).permit(:customer_name)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :customer_name %>
    <%= form.text_field :customer_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-sm btn-outline-secondary" type="button">
      <%= link_to 'Drink Refill', waitstaffs_path %>
    </button>

    <button class="btn btn-sm btn-outline-secondary" type="button">
      <%= link_to 'Request Waiter', waitstaffs_path %>
    </button>
      <button class="btn btn-sm btn-outline-secondary float-left" type="button">
        <%= link_to 'Pay Now/ View Order', waitstaffs_path %>
      </button>
    </form>

  </form>
</nav>

<h1>Customers</h1>

<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Save changes</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to "Menu", menus_path %>
</button>

<!-- START: Welcome to Suit and Thai -->
  <div class="jumbotron">
    <h1 class="display-4">Welcome to Suit and Thai</h1>
    <!-- <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">-->

    <p>How many persons are in your party?</p>
    <a class="btn btn-primary btn-lg" href="managers" role="button" onclick="setPartySize(1)">1</a>
    <a class="btn btn-primary btn-lg" href="#welcome" role="button">2</a>
    <a class="btn btn-primary btn-lg" href="#" role="button">3</a>
    <a class="btn btn-primary btn-lg" href="#" role="button">4</a>
    <!-- //Maybe there should be a dynamic table in the database that holds the number of customers at a table at a given time -->

    <!--
    <button onclick="setPartySize(1)">1</button>
    <button type="button" class="btn btn-outline-secondary btn-lg"><%= link_to '2', managers_path %></button>
    -->
    <script>
      function myFunction(int partySize) {
      /*  thisTable.setPartySize(partySize); 
      */
      int x = partySize; 
      //window.alert(x);
      document.getElementById("partySize").innerHTML = x;
      //Could maybe do a window alert for the coupon question?
      window.alert("");
      }
    </script>

  </div>
<!-- END: Welcome to Suit and Thai -->

<!-- START: "New Customers Junk" -->
</br></br>
<table>
  <thead>
    <tr>
      <th>Customer name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.customer_name %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Customer', new_customer_path %>
<!-- END: "New Customers Junk" -->

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer name:</strong>
  <%= @customer.customer_name %>
</p>

<button type="button" class="btn btn-secondary btn-lg btn-block"><%= link_to "Menu", menus_path %>
</button>

<%= link_to 'Add Another', new_customer_path %> |
<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>